LIBRARYIMAGE-2 : Moved to GitHub ; upgrade to global-pom 3.0.11
This plugin doesn't compile against jdk1.7+ :
    error: package com.sun.image.codec.jpeg does not exist

Because the global-pom sets 1.7 for the java target, force it
to java 1.6 temporarily until it works with newer java versions

git-svn-id: http://dev.lutece.paris.fr/svn/lutece/portal/trunk/plugins/library/library-image@87850 bab10101-e421-0410-a517-8ce0973de3ef